module.exports = {
    projects: [
        {projectName: "Test 1",
         clientName: "California Company",
         projectType: "Project Type",
         projectStartDate: "1/3/2018",
         projectEndDate: "1/5/2019",
         projectContractAmount:"$1,000,000",
        businessUnit: 'LBU',
         ps: 'test ps',
         status: 'incomplete',
         engagementDirector: "Dave Stockman",
         ad: 'test AD',
         notes: "test notes"},

         {projectName: "Test 2",
         clientName: "Maryland Company",
         projectType: "Project Type",
         projectStartDate: "1/3/2018",
         projectEndDate: "1/5/2019",
         projectContractAmount:"$2,000,000",
        businessUnit: 'LBU',
         ps: 'test ps',
         status: 'incomplete',
         engagementDirector: "Dave Stockman",
         ad: 'test AD',
         notes: "test notes"},

         {projectName: "Test 3",
         clientName: "Illinois Company",
         projectType: "Project Type",
         projectStartDate: "1/3/2018",
         projectEndDate: "1/5/2019",
         projectContractAmount:"$3,000,000",
         businessUnit: 'LBU',
         ps: 'test ps',
         status: 'incomplete',
         engagementDirector: "Dave Stockman",
         ad: 'test AD',
         notes: "test notes"
        },

         {projectName: "Test 4",
         clientName: "Boston Company",
         projectType: "Project Type",
         projectStartDate: "1/3/2018",
         projectEndDate: "1/5/2019",
         projectContractAmount:"$4,000,000",
        businessUnit: 'LBU',
         ps: 'test ps',
         status: 'incomplete',
         engagementDirector: "Dave Stockman",
         ad: 'test AD',
         notes: "test notes"},

         {projectName: "Test 5",
         clientName: "Florida Company",
         projectType: "Project Type",
         projectStartDate: "1/3/2018",
         projectEndDate: "1/5/2019",
         projectContractAmount:"$5,000,000",
        businessUnit: 'LBU',
         ps: 'test ps',
         status: 'incomplete',
         engagementDirector: "Dave Stockman",
         ad: 'test AD',
         notes: "test notes"},

         {projectName: "Test 6",
         clientName: "Raymond Company",
         projectType: "Project Type",
         projectStartDate: "1/3/2018",
         projectEndDate: "1/5/2019",
         projectContractAmount:"$6,000,000",
        businessUnit: 'LBU',
         ps: 'test ps',
         status: 'incomplete',
         engagementDirector: "Dave Stockman",
         ad: 'test AD',
         notes: "test notes"},
    ]
}